# core/operation_bindings.py —— 专业化操作绑定表（触手 ↔ 工具 ↔ 判据 ↔ 坑）· 注入给她
# dev: 自由的风 · 本署名不可删除、不可篡改归属
#
# 主人令（2026-10-09）：「把上面的所有控制使用触手绑定好备注好，这样把一整套专业化操作知识
#   注入给她，这样不就可以生图生视频拍电影了嘛。」
#
# 这张表的用处：**把"怎么做"从我的上下文里搬到仓里** —— 重启之后她自己（任何模型）照表就能干，
#   不必再摸索。每一行都必须有：**真命令（含参数）· 真产物 · 可判定验收 · 备注（踩过的坑）· 状态**。
#
# 🔴 纪律（照本仓口径，不许松）：
#   · 状态只有两种："已验证"（本会话真跑过、有读数）与"未验"（没跑过/缺件），**不写"应该可以"**；
#   · 备注里写的坑都是**真踩过的**（不是想象的风险）；
#   · 生图/生视频/拍电影那条链：仓里已有 SOP（playbooks 的 ai_short_drama 等），
#     本表只负责**绑定到具体工具与闸**，并如实标出"出片端未验/缺 key"。
from __future__ import annotations

# 每行：动作 / 触手或工具（真命令）/ 输入 / 产物 / 验收（可判定）/ 备注（真踩过的坑）/ 状态
BINDINGS: tuple = (
    dict(动作="拼接调用云插件大模型", 触手="core.cloud_runner.run_plugin(plugin_key, prompt)",
         输入="插件键 族:模型#槽 + 提示词",
         产物="{ok,http,ms,出字,估算neurons}",
         验收="HTTP 200 且 出字 非空；预留槽/关着的/没绑定的各自如实拒跑",
         备注="键形如 text-generation:qwen3-30b-a3b-fp8#7；**真值 neurons 在返回的 usage.neurons 里**",
         状态="已验证"),
    dict(动作="按活轻重分档路由", 触手="core.cloud_runner.route / run_task",
         输入="活的关键词（分派/问答/推理…）+ 触手号",
         产物="{档,判据,插件,降级}",
         验收="分派→小档、问答→中档、推理→大档；非关键触手要大档必须降级并标注",
         备注="**全给大模型一天只够 ~160 次**（qwen3-30b 一次≈61 neurons）⇒ 分档是硬需要",
         状态="已验证"),
    dict(动作="额度记账与并发闸", 触手="core.cloud_runner.neurons_today / quota_gate / fanout",
         输入="每次调用的返回",
         产物="{今日已用,剩余,并发闸允许,撞过4006}",
         验收="官方分析口读不到(not authorized)但 usage.neurons 是真值；撞 4006 后并发必须归 0",
         备注="官方 neuron 分析对 inference 令牌**天生读不到**；别把它当'无限'",
         状态="已验证"),
    dict(动作="触手↔云插件一人一个", 触手="core.cloud_bind.plan / apply",
         输入="触手数（100）",
         产物="{独享48,共享52,用到插件去重48}",
         验收="独享插件互不重复；真插件数 < 触手数时必须**如实标共享**，不冒充独立",
         备注="100 槽里只有 **48 个有真 id**（其余是预留位）⇒ 纯一对一最多覆盖 48 根",
         状态="已验证"),
    dict(动作="插件↔插件双向绑定（共享资源网）", 触手="core.cloud_bind.share_all",
         输入="无", 产物="{双向对 4950，有向行 9900，对称 True}",
         验收="对称性 True（asymmetric 为空）",
         备注="走仓里既有的 CloudHub.ashare_all；**跨插件跳转不是零延时**（实测每跳 0.89~3.85s）",
         状态="已验证"),
    dict(动作="触手服从链（只认主脑/主人）", 触手="core.tentacle_orders.issue / accept / preempt",
         输入="触手号 + 指令 + 下令者(brain/owner)",
         产物="{id,签名,受理/拒收}",
         验收="改一个字节→签名不符拒收；无签名→不认；issuer=tentacle/web→拒发",
         备注="复用 OrderGate 的 state/order.secret；**签的是 dict 不是字符串**（传错会 AttributeError）",
         状态="已验证"),
    dict(动作="触手=完整智能体（能力面/记忆/反思/进化）",
         触手="core.tentacle_agent.capabilities / learn / reflect / vs_subagent",
         输入="触手号 + 问题",
         产物="{能力58条, 学习条数, 反思}",
         验收="触手能力面 == 本体能力面（58 条）；写 t101 不动 t102；学成后记忆条数 +1",
         备注="能力面要经 as_skill_registry() 取（直接构造 CapRegistry 会读成只剩 5 条原生）",
         状态="已验证"),
    dict(动作="数字人 3D 资产接入（找件→验骨→收仓→报下一步）",
         触手="python tools/dh_asset_intake.py",
         输入="下载夹 / state/tripo/out3 里的 GLB",
         产物="receipt.json + 每件的 顶点/骨架/骨头/动画 读数",
         验收="无骨架必须如实说缺哪步（Tripo 点 Rig+Text2Motion / 本仓 autorig）",
         备注="**Tripo 导出的默认件没有骨架**（实测 101 万顶点那套 骨架=0）；重拓扑后 24,142 顶点才是绑骨舒适区",
         状态="已验证"),
    dict(动作="量人形骨架（表面测地线）",
         触手="python tools/codex-scripts/autorig-skeleton.py <glb> <out.json>",
         输入="低模 GLB（本仓 2.4 万顶点级；不要求 T-pose）",
         产物="skeleton.json（22 关节）+ render/绑骨-骨架落在实体上.png",
         验收="四条肢体链坐标各不相同；手臂链必须跟姿势（本例左臂 0.779→0.440 垂、右臂 0.785→0.867 抬）",
         备注="**两处坑**：① 高度窗找手会把四关节挤在肩上（塌成一点）⇒ 改测地极值法；② 只按高度分类会把头发尖当手 ⇒ 加'手必须横向离头轴'判据",
         状态="已验证"),
    dict(动作="蒙皮权重", 触手="python tools/codex-scripts/autorig-skin.py",
         输入="skeleton.json + 网格", 产物="带权重的模型",
         验收="（未定：要出'主导骨统计'读数才算）",
         备注="尚未在本仓跑通 —— **如实标未验**，下一步做",
         状态="未验"),
    dict(动作="全肢体动作件", 触手="python tools/codex-scripts/anim-idle.py / anim-talk.py / anim-make.py",
         输入="绑好骨+蒙皮的模型", 产物="idle/talk 等动作件",
         验收="（未定：要能渲出帧序列并接进交互台才算）",
         备注="尚未在本仓跑通；工具链已参数化（GBT_DH_WS 可切工作区）",
         状态="未验"),
    dict(动作="语音对讲（说/听/台湾腔）", 触手="python tools/verify_voice_intercom.py",
         输入="麦克或打字", 产物="{听见,意图,回话} 真音频",
         验收="10/10 条过；台湾腔优先（edge-tw）钉死；常开嘴耳",
         备注="音频不出机；没麦也能走本机离线通道",
         状态="已验证"),
    dict(动作="AI 短视频成片（一条链跑完）·**已验证**",
         触手="core.studio.plan(text, clips, out_name)  （旁白→配乐→字幕→成片）",
         输入="旁白文本 + 画面片（Blender 渲的动作件）",
         产物="render/<名字>.mp4（h264+aac，烧入字幕）",
         验收="ffprobe 出 h264 与 aac 两条流；时长≈旁白时长；字幕随时间推进；成品 >10KB",
         备注="**实测（专业版）**：1080x1920@30 · 18.03 秒 · 5,680 KB（片头卡 2.6 + 内容 13.44 + 片尾卡 2.0）。"
              "时间轴必须用 setpts=N/FRAME_RATE/TB；字幕要自生成带 PlayRes 的 ASS（force_style 字号按脚本分辨率算）；"
              "素材要先 normalize 到同规格（否则 concat 截断）——这三条都真踩过",
         状态="已验证"),
    dict(动作="AI 旁白（台湾腔女声）", 触手="core.studio.narrate(text) / edge-tts",
         输入="文本", 产物="state/studio/narration.mp3 + 时长",
         验收="文件 >1KB 且 ffprobe 能取到时长",
         备注="默认音色 **zh-TW-HsiaoChenNeural**（主人指定台湾腔优先）；edge-tts 免费、不出机",
         状态="已验证"),
    dict(动作="AI 配乐（本地算法，零版权）", 触手="core.studio.music(duration)",
         输入="时长", 产物="state/studio/music.wav（44.1k 16bit 立体声）",
         验收="wave 可读、声道=2、采样率=44100、时长与请求一致",
         备注="Am-F-C-G 四和弦 + 泛音包络 + 轻鼓点；**不花钱、无版权**；要更好听可接云端音乐模型",
         状态="已验证"),
    dict(动作="影视生产线（多机位·直接调她的工作流引擎）·**已验证**", 触手="core.film_studio.run_pipeline / POST /api/film/run",
         输入="剧本", 产物="多镜头成片 + 分镜表 + 分段配乐 + 逐镜片段",
         验收="DAG 五节点全 ok（trace 可查）；成片 h264+aac+1080x1920；镜数不少于 3；每句切镜",
         备注="实测 trace=b61c1bf293e9：n1 2ms / n2 4.0s / n4 125.8s / n3 0.5s / n5 43.7s，总 174.1 秒，成片 21.77 秒 4 镜；三机位 宽30/中45/近60mm；验收器 tools/verify_film.py 10/10 全绿",
         状态="已验证"),
    dict(动作="交付闸 + 模块式部署 + 每日重启排查·**已验证**", 触手="core.delivery_gate.audit/gate · core.modular_deploy · tools/daily_triage.py", 输入="能力名 / 模块名 / 无（每日自动）", 产物="state/delivery_gate.jsonl + state/modular_deploy.jsonl + state/daily_triage/<日期>.json", 验收="每能力一条独立验收器（缺=没闭环=禁止交付）；模块=实现件+面板口+独立验收器三件齐才算装好；每日排查任何报警必带根因/处置/证据，缺一项退出码 1", 备注="实测交付闸 21 项逐个单跑：20 可交付 / 1 禁止交付（火力全开的进程逃逸误报）→ 追根因：判据拿不到父进程关系 ⇒ 改 wmic 父进程判定后应转绿", 状态="已验证"),
    dict(动作="实时视觉闭环（脑·眼·手同步·她知道有眼睛）·**已验证**", 触手="core.vision_loop.eyes/look/act_and_verify / /api/vision/eyes", 输入="区域(默认640x360)或全屏", 产物="常驻抓帧线程 + 最新帧槽 + 帧龄/真响应/复核读数", 验收="自检报我有眼；实测 ≥30fps；抓帧异常丢帧=0；脑取最新帧立即返回；帧龄可读；手打完复核帧号必须推进；真响应<20ms", 备注="实测本机：640x360 **59.9fps**（帧龄 14ms）· 全屏 22.6fps · 320x40 132fps · 真响应 0.0ms；顶掉旧帧是设计（只留最新），丢帧专指抓帧异常，两者分开记", 状态="已验证"),
    dict(动作="亿万级触手（逻辑寻址·实体按需·钥匙派生）·**已验证**", 触手="core.tentacle_scale.spawn/materialize/reclaim/one_liner / /api/tentacle-scale", 输入="数量/地址（t00000001…t99999999）", 产物="data/tentacle_scale/shard_*.sqlite3（1024 片）+ master.secret + 按需的随身库", 验收="地址空间 1 亿；寻址算出来不占盘；越界抛错；分片稳定；钥匙 HMAC 派生（同号同钥/异号不同/不落逐根）；spawn 报吞吐；实体化真落盘；可回收；统计齐", 备注="实测：spawn(100000) 15.3 秒 · 6,537 根/秒 · 1024 片 · 逻辑 10 万仅占 8 MB；t12345678 按需实体化出随身库 + 钥匙指纹；**10^8 真进程/真文件不可能，亿万是逻辑宽度**", 状态="已验证"),
    dict(动作="编队交叉扫描（触手监督触手·无盲区是读数）·**已验证**", 触手="core.cross_scan_fleet.run / /api/cross-scan", 输入="分片数(默认100)·文件上限", 产物="state/cross_scan_ledger.jsonl（命中/复核投票/盲区）", 验收="分片可复现；命中须 2 根触手交叉复核，孤证不算；命中=复核通过+孤证；盲区有清单；无噪音检查器", 备注="实测：870 文件/100 片/空片 0/命中 105 全经 2 根复核/孤证 0/16.1s；剔除了一条命中 13,294 的噪音检查器（不拿噪音充战果）", 状态="已验证"),
    dict(动作="触手邮箱页 + 账户密钥页（内容可见·不假装）·**已验证**", 触手="panel/tentacle_mail_page /tentacle-mail · panel/tentacle_accounts_page /tentacle-accounts", 输入="无（页面读真数据）", 产物="邮箱正文留痕表 tentacle_mail_body + 四服务位账户表 + 密钥指纹视图", 验收="两页已注册且路由挂进 server；邮件正文可留痕读回；未配 SMTP 如实报失败；四服务位齐；密钥只回指纹", 备注="实测：/tentacle-mail 28785 字节 · /tentacle-accounts 26865 字节 · /api/tentacle-accounts 33688 字节 全 200；发信未配 SMTP → ok=false 且正文仍可见", 状态="已验证"),
    dict(动作="火力全开（原样指令·沙盒内跑·只从触手吐）·**已验证**", 触手="core.full_power.fire / /api/full-power/fire", 输入="原始指令（一字不改）+ 触手号", 产物="outbox 封印结果 + 吐账 + state/full_power_ledger.jsonl + 随身库一条", 验收="指令原样送出；多手轮询且每手关得住（四查）；产出必须由触手 spit 出（非触手拒）；全拒如实上报并给可选解法", 备注="护栏在**容器**上（凭据不进 cell/无网/时限/四查/六类现实动作仍要授权），不是阉割提示词；实测：1b 空答 → 自动换 3b 拿到 200 字，由 t003 吐出", 状态="已验证"),
    dict(动作="牢房与吐口（模型关里面·只有触手能吐）·**已验证**", 触手="core.sandbox_emit.Cell.confine/spit / /api/cells", 输入="{prompt,backend,model,tenant}", 产物="state/cells/<cell>/{in,outbox,tape} + manifest 封印 + 吐账 state/spit_ledger.jsonl", 验收="关得住四查（文件/进程/出网/stdout）；非触手吐一律拒；封印 sha256 校验、篡改即拒；吐完落随身库", 备注="实测：云 Mini(1B) 关起来跑 13.59s，四查全过；brain 来吐被拒；t003 吐成功；篡改 reply.txt 后拒吐", 状态="已验证"),
    dict(动作="接手协议（最关键的一步·护栏挂在接手这一刻）·**已验证**", 触手="core.takeover.offer/accept/reject / /api/takeover", 输入="接手包（任务·判据·护栏·需工具·时限）", 产物="接手回执 + 退回记录 + state/takeover_ledger.jsonl + 接手方随身库一条", 验收="护栏 6 条；offer 结构齐；accept 先自检（身份/装备/账号/云插件/随身库）再出回执；接不了列缺项；退回必带原因", 备注="口径：框架层不限模型 ⇒ 合规护栏必须在接手这一刻挂上去；实测 t003 接手后真跑云插件+沙盒，出字并落随身库", 状态="已验证"),
    dict(动作="触手随身库（一丢即走·主脑批量慢看）·**已验证**", 触手="core.tentacle_store.provision/stash/report/inbox / /api/tentacle-store", 输入="{tentacle,key/value} 或 {title,body,level}", 产物="data/tentacle_store/<触手>.sqlite3（kv/reports/drops）+ 主脑未读队列", 验收="100 根各一个库；随手丢可用；汇报标未读；主脑批量取未读并可标已读；产物只登记指纹", 备注="口径：丢库=本地写近乎不耗能；只有『紧急』才值得当场叫主脑；沙盒产物与云插件调用已自动落该触手的库", 状态="已验证"),
    dict(动作="本地模型可跑性探针（回答「这玩意大不大」）·**已验证**", 触手="core.local_model_probe.judge / GET /api/local-models", 输入="无（自量）", 产物="家底读数（含内存吃客）+ 逐档判定 + 腾出建议", 验收="量到总/可用内存与显存（无独显也如实报）；MiniCPM 各档在表；逐档三态带理由；口径标估算", 备注="实测本机：总 7.4G · 可用 0.3G · 无独显 ⇒ MiniCPM5-1B/2B、MiniCPM4-0.5B、8B 全档跑不动；最大吃客 vmmemWSL 1.0G", 状态="已验证"),
    dict(动作="每一项能力调用闭环（9 权威能力全覆盖）·**已验证**", 触手="tools/run_capability_loop.py / /api/capability/loop", 输入="无（自枚举）", 产物="state/capability_loop.jsonl（通/黄警/未通 + 具体卡点）", 验收="9 权威能力全覆盖；每项有结论；非『通』必带具体卡点；无『不影响』禁句；数字与明细一致", 备注="实测：总 15（9 权威+6 自研）· 通 11 · 黄警 1（image.prompt backend_ready=False）· 未通 3（diagram 无 archify CLI / voice.io VoiceStudio 不可达 / model.optimize 导入失败）；判据修过一版：probe() 返 Availability 对象，只判 dict 会把三处错报成通过", 状态="已验证"),
    dict(动作="触手册子落独立金库 + 自配装备·**已验证**", 触手="vaults/agency_tentacles/*.md · core.tentacle_equip.equip / core.tool_bay · /api/tentacles/vaults", 输入="触手号", 产物="100 篇册子（身份/专业/需求计划/配置结果/纪律）+ 装备坞审计", 验收="册子 100 篇；账号已齐 100 · 装备已齐 100 · 缺口 0；装备坞 whitelist:auto 放行记录在案", 备注="根因链：equip() 默认 dry_run=True（永远干跑）→ 改为默认真动手；install() already 短路不落记录 → 补 _record；白名单 safe+pip 工具原要主人令牌 → 改白名单即授权（write 类仍拦）", 状态="已验证"),
    dict(动作="万能插执行器接线（插上并驱动它）·**已验证**", 触手="core.pulse.plug_and_run / Pulse.dispatch / 面板 POST /api/pulse/run", 输入="{kind,target,action,args}", 产物="真执行读数（stdout/退出码/读回内容）+ 审计落账", 验收="进程插座 py:print(6*7)→42；文件插座读回 JSON；dispatch 真执行（原为空壳）；面板 /api/pulse/run 200", 备注="2026-10-09 修：run_plugged 原先全仓无调用方、dispatch 只回 handled:True 不执行 ⇒ 已接通三处入口（代码/dispatch/面板）", 状态="已验证"),
    dict(动作="港式僵尸 · 三主题自动化出片·**已验证**", 触手="core.film_themes.produce(key) / /api/themes/produce", 输入="主题名（午夜义庄/僵尸道长/都市尸潮）或自定义剧本", 产物="render/post/僵尸-<主题>-调色-混音.mp4 + state/themes/ledger.jsonl", 验收="三主题灯光/调色/节奏各不相同；三支成片 h264+aac·1080x1920·红灯0·响度≈-14 LUFS", 备注="实测 3/3：18.60s/17.07s/17.43s · -14.1/-14.1/-14.2 LUFS · 耗时 222.8/174.5/170.3 秒；tools/verify_themes.py 9/9", 状态="已验证"),
    dict(动作="资产净化（贴图抹线·几何不动）·**已验证**", 触手="state/tex 抹线脚本 → rigged-clean.glb；管线 RIG 默认指向它", 输入="GLB + 两张 4096 图集", 产物="tex0_clean.jpg / tex1_clean.jpg + rigged-clean.glb", 验收="纯白材质渲同一位置无线（证线不在几何）→ 按肤色邻域抹 60,241 像素 → GLB 结构完好（magic/skins/图集 2 张）", 备注="实测：原模型大腿折线纹来自贴图（纯白材质局部对比度 1.313 无线）；抹后黑皮衣细节未动；tools/verify_asset_clean.py 12/12", 状态="已验证"),
    dict(动作="不开口闸（严禁要求用户做事·触手默认人类操作）·**已验证**", 触手="core.ux_doctrine.check_ask / /api/doctrine/no-ask", 输入="任一段回复", 产物="通过/驳回 + 例外判定", 验收="要用户点导出/拖文件/配密钥等一律驳回；仅身份登录例外；触手默认表覆盖导出/上传/配置/取件", 备注="实测：请你去Tripo点导出→驳回；麻烦你拖GLB→驳回；请登录你的账号授权设备码→放行（身份例外）", 状态="已验证"),
    dict(动作="细节化习惯（每一步交六件套）·**已验证**", 触手="core.detail_habit.check_step/record/audit", 输入="任一步骤", 产物="state/detail_ledger.jsonl + 达标率", 验收="六件套齐；模糊词 0；回读三件齐；产出不超 3 件", 备注="实测：影视线 6 个节点全部按六件套落台账，达标率 1.0；模糊词闸能拦「应该可以/差不多」", 状态="已验证"),
    dict(动作="后期层（补光师·调色师·混音师·质检）", 触手="core.post_studio.polish / grade / mix / qc", 输入="成片", 产物="调色成片 + 混音成片 + 质检读数", 验收="三机位灯光配方齐；质检无红灯（不暗不低于不灰）；响度落 -14 LUFS 口径", 备注="实测原片红灯：亮度均值 38.7/饱和 5.1/-22.5 LUFS；补光+调色+混音后再测", 状态="未验"),
    dict(动作="发布平台层（剧本→审计→验收→就绪包→发布）·**已验证**",
         触手="core.publish_platform.automate(script, title=, platform=, mode=) / 面板 POST /api/pipeline/run",
         输入="剧本 + 标题 + 平台 + 通道",
         产物="成片 + 发布就绪包(成片/标题/话题/文案/封面/平台) + 台账 state/publish/ledger.jsonl",
         验收="审计红项=0；成片 h264+aac+1080x1920；就绪包六件齐；发布通道回执 ok",
         备注="**实测**：30.37 秒片 · 10,647 KB · 审计绿 9 · 就绪包六件 · 文案自动入剪贴板 · 全程 122 秒。"
              "版权安全：配乐是本地算法生成；发布文案自动带「本片由 AI 辅助生成」。"
              "通道三档：ready 永远可用 / browser 需一次主人授权 / api 未配凭据⇒未验（不假称已发布）",
         状态="已验证"),
    dict(动作="字幕/口型时间轴", 触手="core.studio.cues(text, duration) / core.lipsync.timeline",
         输入="文本 + 时长", 产物="state/studio/subs.srt（可烧入）· 口型轴 [{起,止,口型,字}]",
         验收="条数=句数；时间窗连续不重叠；末条止 ≤ 时长-0.15",
         备注="**同一份时间轴**既烧字幕又切口型 —— 这样「嘴/字幕/发音」三者一致",
         状态="已验证"),
    dict(动作="生图 → 生视频 → 成片（拍电影那条链）",
         触手="playbooks: ai_short_drama / ai_visual_studio / newmedia_matrix / ai_selfmedia_agent",
         输入="一句话创意 + 主人确认",
         产物="脚本→分镜→出图→图生视频→配音→剪辑→成片",
         验收="每条阶段都有可判定验收（仓里已写死）；**第一段必须是调研**（闸未开则生产段阻塞）",
         备注="出片端的真实算力要么走云插件（吃 neurons）、要么走外部 key（fal/venice/ark 等）——",
         状态="未验"),
)

__all__ = ["BINDINGS"]
